version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "=== Starting INSTALL phase ==="
      - echo "Current working directory: $(pwd)"
      - echo "Listing project files:"
      - ls -R
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t package
      - cp app.py package/
      - cd package
      - zip -r ../lambda.zip .

  build:
    commands:
      - echo "=== Starting BUILD phase ==="
      - echo "Build completed."

  post_build:
    commands:
      - echo "=== Starting POST_BUILD phase ==="
      - echo "Uploading lambda code to S3..."
      - aws s3 cp ../lambda.zip s3://class3-assign-lambda-deploymentfiles/lambda.zip

      - echo "Updating Lambda function..."
      - aws lambda update-function-code \
        --function-name class3-assign-doordash-lambda \
        --s3-bucket class3-assign-lambda-deploymentfiles \
        --s3-key lambda.zip

      - echo "Waiting 10 seconds for Lambda update to complete..."
      - sleep 10

      - echo "Uploading sample JSON file to landing bucket..."
      - aws s3 cp data/doordash_input.json s3://class3-assigno-doordash-landing-zn/doordash_input.json
